-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD B 
JOIN USED_GOODS_REPLY R
ON B.BOARD_ID = R.BOARD_ID
WHERE DATE_FORMAT(B.CREATED_DATE, '%y-%m') = '22-10'
ORDER BY R.CREATED_DATE, B.TITLE

# SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
# FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B 
# WHERE A.BOARD_ID = B.BOARD_ID
# AND A.CREATED_DATE LIKE '2022-10%'
# ORDER BY B.CREATED_DATE ASC, A.TITLE ASC;